name: 'get and cache requirements'
description: 'Update python, get and cache requirements'
runs:
  using: 'composite'
  steps:
    - name: Update Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache virtual environment
      id: cache-venv
      uses: actions/cache@v4
      with:
        path: .venv  # Cache the virtual environment
        key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-            

    - name: Create virtual environment
      if: steps.cache-venv.outputs.cache-hit != 'true'  # Only create if cache is missing
      run: python -m venv .venv
      shell: bash

    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
