name: Run LLM integration Tests
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # To read the repository contents (for `actions/checkout`)
      id-token: write  # To use OIDC for accessing resources (if needed)
      actions: read  # Allow the use of actions like `actions/cache`

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update python and install dependencies
        uses: ./.github/actions/cached-requirements

      - name: Install test dependencies
        run: |
          source .venv/bin/activate
          pip install pytest            

      - name: Get AWS Permissions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/sql-data-guard-github-role-for-bedrock-invoke
          aws-region: us-east-1

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          PYTHONPATH=src python -m pytest --color=yes test/test_sql_guard_llm.py