name: Run Unit Tests
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # To read the repository contents (for `actions/checkout`)
      actions: read  # Allow the use of actions like `actions/cache`

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update python and install dependencies
        uses: ./.github/actions/cached-requirements

      - name: Install project and test dependencies
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt  # Install main project dependencies
          pip install -r test/test_requirements.txt  # Install additional test dependencies

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          PYTHONPATH=src python -m pytest --color=yes test/*_unit.py